// TEMPORARY one-shot maintenance endpoint — removed in the next commit.
// Fills in full product descriptions for products that had boilerplate/short
// copy. The four MADE TO LAST. products use their local Listings.md; the rest
// are written fresh in the Arwign voice. Idempotent (keyed on slug).
// Guarded by the SHA-256 of a random 384-bit token.
import { createClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'
import { createHash, timingSafeEqual } from 'node:crypto'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

const TOKEN_SHA256 = '43b0f1af51ee08b61c62dd7c4df509dc903da986299cdd14b13acb338685eeb8'

// slug -> HTML description
const DESC: Record<string, string> = {
  // ── MADE TO LAST. set (from local Listings.md) ─────────────────
  'made-to-last': `<p><strong>Three books. One business. A structure designed to last.</strong> MADE TO LAST. is a set of three linked digital planners for the solo creative turning craft into income — makers, digital product sellers, commission artists and people who teach their craft. Each book does one job well; together they hold the whole business.</p><p><strong>GROUNDWORK. — the foundations (160 pages).</strong> Where you stand and why you make, your offer ladder and product sheets, customer profiles, brand and story, pricing models, channels, SOP templates, and a 12-month growth map.</p><p><strong>THE LONG YEAR. — the operating year (420 pages).</strong> An undated year in four quarters and twelve months, with 53 Make / Sell / Admin weekly spreads, quarterly goals, 90-day plans, monthly reviews, and project, launch and market planners.</p><p><strong>THE COUNT. — the money (220 pages).</strong> From your minimum hourly rate to the year-end pack for your accountant: costing, ledgers, monthly P&Ls, cashflow, tax set-asides, invoices and profitability.</p><p>Three separate A4 PDFs, hyperlinked within each book, undated and currency-neutral, for GoodNotes, Notability and other PDF apps. Instant download — buy the set and save.</p>`,

  'groundwork': `<p><strong>The foundations planner for the solo creative turning craft into income.</strong> Most makers don't struggle with the craft — they struggle with everything around it: pricing, channels, systems, admin, and knowing what "enough" looks like. GROUNDWORK. walks you through all of it in 160 calm, practical, fully hyperlinked A4 pages.</p><p>Work out your "enough" number and a pricing model for every way you earn — made goods, digital products, commissions and workshops. Map three customer profiles and their journey. Build an offer ladder with ten product sheets. Write down how every job is done once, with workflow maps and SOP templates, so you stop running the business from memory. Then set a twelve-month growth map.</p><p>Book one of MADE TO LAST., with handover pages into THE LONG YEAR. and THE COUNT. A4 hyperlinked PDF, undated, for GoodNotes and Notability. Instant digital download.</p>`,

  'the-long-year': `<p><strong>A year of steady weeks builds a business that lasts.</strong> THE LONG YEAR. is the undated operating year for the solo creative turning craft into income. Every week is split into three lanes — Make, Sell and Admin — so no part of the business gets quietly neglected, and every month and quarter ends with an honest review.</p><p>It's 420 fully hyperlinked A4 pages: 53 weekly spreads (a plan, hour-by-hour time blocks and a Friday close-out), twelve months (calendar, agenda, content calendar, numbers snapshot and a two-page review), and four quarters (goals by lane, a 90-day plan, marketing and a proper review). Plus the planners behind it all — ten projects, six launches, six markets and events, commissions, wholesale and a ten-page order log.</p><p>Book two of MADE TO LAST. Undated, with a year navigator linking every week and more than 10,800 internal links. A4 PDF for GoodNotes, Notability and other PDF apps. Instant digital download.</p>`,

  'the-count': `<p><strong>Know what every piece costs, what every month earns and what's set aside for tax.</strong> THE COUNT. is the money book for the solo creative turning craft into income. It takes you from your minimum hourly rate to the year-end pack for your accountant, in calm, clear steps.</p><p>It's 220 fully hyperlinked A4 pages across twelve tabbed sections: money foundations, pricing & costing (with a minimum hourly-rate calculator and ten product costing sheets), income and expense ledgers, monthly and quarterly P&Ls, cashflow forecasts, tax set-asides with an accountant handover pack, invoices and payments, stock and materials, profitability by product and channel, funds and assets, and a full year-end review.</p><p>Book three of MADE TO LAST. Undated and currency-neutral — no currency symbols are printed anywhere, so you write figures in your own currency. A4 PDF for GoodNotes, Notability and other PDF apps. Instant digital download. General guidance only; not tax or financial advice.</p>`,

  // ── Business planners ──────────────────────────────────────────
  'paid': `<p><strong>Look as professional behind the scenes as you do on camera.</strong> PAID. is a dedicated brand-deal and UGC planner for content creators, so every pitch, brief, deliverable and payment finally has a proper home instead of a midnight scroll back through your DMs.</p><p>Track the whole pipeline: log pitches and their status, build a rate card you can quote from with confidence (base content, add-ons, usage rights and exclusivity), capture each brief so "one more version" is never a surprise, follow deliverables from draft to live, and chase every invoice until it's paid. When a brand asks for your numbers, you're ready.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF annotation app. Pairs with WHAT WORKS., our analytics planner. Instant download, undated and reusable.</p>`,

  'what-works': `<p><strong>Make decisions from evidence, not guesswork.</strong> WHAT WORKS. is a social media analytics planner for creators who want to understand their own audience instead of chasing every trend.</p><p>Give the metrics that actually matter — saves, shares, watch time and retention, engagement rate, follower growth from content, and clicks and conversions — a proper home: weekly logs, post reviews, content experiments and monthly reflections. Each week you record the numbers, notice one lesson, and turn it into next week's plan. Over time you build an understanding of your audience that no algorithm change can take away.</p><p>A hyperlinked digital planner for GoodNotes and Notability. Pairs with PAID., our brand-deal planner. Instant download, undated and reusable.</p>`,

  'in-bloom': `<p><strong>For the season your business starts to bloom.</strong> IN BLOOM is a growth planner for creatives and small-business owners ready to move from getting by to growing on purpose.</p><p>Set a clear vision for where you're headed, break it into seasonal goals, and plan the launches, offers and steady habits that move the work forward — with space to track what's flourishing and prune what isn't earning its place. Warm, considered pages that make the business side feel as intentional and cared-for as the work itself.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'yes-i-do-wedding-planner': `<p><strong>Everything for the big day, in one calm place.</strong> Yes, I Do is a complete wedding planner for couples who'd rather enjoy the engagement than drown in spreadsheets and open tabs.</p><p>Plan it end to end: a countdown and timeline, budget and payment trackers, the guest list and RSVPs, vendor research and contacts, venue and catering, attire, décor and flowers, the ceremony and reception running order, seating, and a day-of schedule so nothing is left to memory. Room for the details that make it yours, and checklists that keep the whole thing moving.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app — print pages at home if you prefer. Instant download, undated and reusable.</p>`,

  // ── Habit / wellness ───────────────────────────────────────────
  'arwign-66-day-habit-tracker': `<p><strong>Built on how habits actually form.</strong> The myth says 21 days; the research puts the real average nearer 66. The Arwign 66-Day Habit Tracker is designed around that longer, truer arc, so you give a new habit the time it genuinely needs to become automatic.</p><p>Track up to a handful of habits across the full 66-day window, log the trigger and cue behind each one, and watch the streak build day by day. Gentle review prompts help you spot what's sticking, what needs a smaller version, and what to keep once it no longer needs tracking at all.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app — or print it at home. Instant download, undated and reusable.</p>`,

  'arwign-wellness-planner': `<p><strong>A gentle, whole-life wellness companion.</strong> The Arwign Wellness Planner brings the quiet pieces of looking after yourself — mood, sleep, movement, water, gratitude and rest — into one calm place, without the pressure of a rigid regime.</p><p>Check in with how you're actually feeling, track the small daily habits that keep you steady, and use the weekly and monthly reflection spreads to notice what restores you and what drains you. Designed to meet you on an ordinary week, not just your best one.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'ebb-flow-energy-fatigue-planner': `<p><strong>Plan around the energy you actually have.</strong> Ebb & Flow is an energy and fatigue planner for anyone whose capacity isn't the same every day — living with chronic illness, burnout, or simply a body that has good weeks and hard ones.</p><p>Check in on your energy before you plan, give each task a rough cost, and spend what you have on what matters most while keeping a little in reserve. Track your patterns over time to see which days run heavy, what drains you, and what quietly gives energy back — so you can stop borrowing from tomorrow.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable. General wellbeing guidance, not medical advice.</p>`,

  'faith-hope-love-the-three-that-remain': `<p><strong>A gentle planner for a life rooted in faith, hope and love.</strong> Faith, Hope & Love — The Three That Remain is a reflective companion for slowing down, giving thanks, and tending the things that last.</p><p>Space for prayer and scripture reflection, gratitude and daily examen, hopes to hold onto, and the relationships you want to pour into. Weekly and monthly pages help you carry intention through an ordinary week, and quiet reflection prompts keep you anchored when life gets loud.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'inner-weather-a-mental-wellness-planner': `<p><strong>Learn to read your own inner weather.</strong> Inner Weather is a mental-wellness planner for noticing how you're really doing — the passing storms and the clear days — and responding with a little more kindness.</p><p>Daily mood and feelings check-ins, thought-download space to empty a full head onto the page, triggers and coping-tool trackers, and weekly and monthly reflections that reveal patterns you can't see day to day. A calm, non-clinical place to tend your mind alongside everything else you carry.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable. A supportive tool, not a substitute for professional care.</p>`,

  'mornings-light-evenings-calm-a-morning-evening-ritual-planner': `<p><strong>Bookend your days with intention.</strong> Morning's Light, Evening's Calm is a ritual planner for the two hinges of the day — a morning that sets the tone before the world rushes in, and an evening that helps you actually put the day down.</p><p>Design a morning routine you'll keep and a wind-down that lets you rest: intention-setting and priorities to start, gentle reflection, gratitude and screens-off cues to close. Habit anchors and trackers help each ritual take root until it feels as natural as making tea.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'open_tabs_adhd_mental_load_planner': `<p><strong>For the days your mind has twenty things open at once.</strong> Open Tabs is an ADHD mental-load planner built for capture-first thinking: a fast, safe place to dump everything rattling around so your brain can stop holding it all.</p><p>Brain-dump pages to clear the noise, then sort into what's actually next; "one small step" prompts that turn a frozen task into a doable first move; energy-aware planning that makes room for both the ten-thing days and the getting-dressed-is-the-win days; and gentle, restart-friendly layouts that never punish a gap. Hyperlinked throughout, so any page is a tap away — never a long scroll.</p><p>A digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable. A supportive tool, not a treatment.</p>`,

  'bloom-where-youre-planted-a-growth-wellbeing-planner-for-students-young-adults': `<p><strong>Grow where you are, at your own pace.</strong> Bloom Where You're Planted is a growth and wellbeing planner for students and young adults finding their feet — balancing study, work, friendships and the quiet work of becoming yourself.</p><p>Set goals that are yours (not someone else's), build steady habits and routines, and check in on mood, energy and wellbeing alongside the practical week. Reflection prompts help you notice how far you've come, and gentle structure keeps you moving without the pressure to have it all figured out.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  // ── Student planners ───────────────────────────────────────────
  'the-balanced-student': `<p><strong>Stay on top of it all without burning out.</strong> The Balanced Student is a complete academic planner for university and college — built for chaotic timetables, competing deadlines, and a life that's more than lectures.</p><p>Map the whole term with semester overviews, weekly study plans, assignment and deadline trackers and exam countdowns, then protect the rest of your life around it with habit, wellbeing and budget pages. See the crunch weeks coming, plan the calm ones, and finish the year steady rather than scrambling.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'the-anxious-students-companion': `<p><strong>A kinder way through the hard stretches of study.</strong> The Anxious Student's Companion is a gentle academic and wellbeing planner for students who feel the weight of it all — the deadlines, the comparison, the what-ifs at 2am.</p><p>Calm study planning that breaks big tasks into small, doable steps, worry-download and grounding pages for the anxious moments, self-talk and reflection prompts, and space to track mood and energy alongside the workload. Structure that steadies you, without pretending the stress isn't real.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable. A supportive tool, not a substitute for professional support.</p>`,

  'living-through-the-burnout': `<p><strong>For the term when you're running on empty.</strong> Living through the Burnout is a gentle student planner for the stretches when everything feels like too much — built to help you keep moving forward without demanding more than you've got.</p><p>Pared-back planning around your real capacity, one-small-thing daily focuses, rest and recovery pages that treat downtime as part of the plan, and honest check-ins that help you spot the warning signs early. It meets you where you are and helps you get through, one manageable day at a time.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable. A supportive tool, not a substitute for professional care.</p>`,

  'pace-dont-race': `<p><strong>Slow is smooth, and smooth is sustainable.</strong> Pace, Don't Race is a student planner for the long game — built to help you make steady, consistent progress instead of the sprint-and-crash cycle that leaves you exhausted by mid-term.</p><p>Break big goals into small weekly steps, plan study in sustainable blocks with real breaks built in, and track progress in a way that rewards showing up rather than heroics. Gentle pacing prompts keep you moving at a speed you can actually hold for a whole semester.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'small-steps-big-dreams': `<p><strong>Big dreams, built one small step at a time.</strong> Small Steps, Big Dreams is a student planner for turning the goals that feel far away into a path you can actually walk — this week, this month, this term.</p><p>Name the big dream, break it into milestones and then into next actions, and use weekly and monthly pages to keep chipping away while life happens around it. Reflection and celebration prompts help you notice progress, so momentum builds instead of fading after the first burst of motivation.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'made-for-my-future-self': `<p><strong>Plan today for the person you're becoming.</strong> Made for My Future Self is a student planner that connects the small daily choices to the bigger picture — the future self you're quietly building with every study session, habit and decision.</p><p>Picture where you want to be, set goals that ladder up to it, and use weekly and monthly planning to keep the day-to-day pointed in that direction. Reflection and vision pages keep the "why" in view on the ordinary weeks, so motivation comes from meaning rather than pressure.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'a-bright-new-dawn': `<p><strong>A fresh start, whenever you need one.</strong> A Bright New Dawn is a student planner for beginnings — a new term, a new year, or simply the decision to start again after a rough patch, without dragging the old weight along.</p><p>Reflect on what worked and what didn't, set clean intentions and goals, and build the study routines and habits to carry them, all with the optimism of a genuinely fresh page. Gentle structure to help you begin again as many times as you need to.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'arwign-planner-ember-edition': `<p><strong>Warm, focused planning for the darker, busier months.</strong> The Arwign Planner — Ember Edition is a student planner dressed for autumn and winter term: cosy tones and calm layouts for the season of deadlines, exams and early nights.</p><p>Everything you need to stay on course — weekly and monthly study planning, assignment and deadline tracking, goals and habits, and reflection pages — with room to look after yourself through the heavier stretch of the academic year.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'arwign-planner-spring-break-edition': `<p><strong>Reset and refocus for the second half of the year.</strong> The Arwign Planner — Spring Break Edition is a student planner for the fresh energy of spring term: a chance to review how the year's gone, tidy up loose ends, and plan the run toward exams with a clear head.</p><p>Weekly and monthly study planning, deadline and assignment trackers, goal-setting and habit pages, and reflection spreads — bright, calm layouts to carry you through to the finish line.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'arwign-planner-summer-break-edition': `<p><strong>Keep momentum through the long break.</strong> The Arwign Planner — Summer Break Edition is a student planner for the months between terms — light enough to enjoy the summer, structured enough to keep your goals from drifting.</p><p>Plan projects, reading, internships or resits without the term-time pressure; set summer goals and gentle routines; and use the reflection pages to arrive at the next term rested and ready rather than scrambling. Airy, relaxed layouts for a slower season.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,

  'arwign-planner-postdoc-sem-edition': `<p><strong>For research life beyond the taught years.</strong> The Arwign Planner — PostDoc / Semester Edition is built for postgraduate researchers and postdocs juggling long-horizon projects with the weekly reality of teaching, writing, admin and a life outside the lab.</p><p>Map the semester and the longer research arc, plan writing and experiments in sustainable blocks, track deadlines, submissions and milestones, and protect time for the work that actually moves your research forward. Structure for the marathon, not just the sprint.</p><p>A hyperlinked digital planner for GoodNotes, Notability and any PDF app. Instant download, undated and reusable.</p>`,
}

export async function POST(req: NextRequest) {
  const token = req.headers.get('x-maint-token') ?? ''
  const presented = createHash('sha256').update(token).digest()
  const expected = Buffer.from(TOKEN_SHA256, 'hex')
  if (presented.length !== expected.length || !timingSafeEqual(presented, expected)) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!)
  const updated: string[] = []
  const failed: Record<string, string> = {}

  for (const [slug, description] of Object.entries(DESC)) {
    const { data, error } = await db
      .from('products').update({ description, updated_at: new Date().toISOString() })
      .eq('slug', slug).select('slug').single()
    if (error || !data) failed[slug] = error?.message ?? 'no row'
    else updated.push(slug)
  }

  return NextResponse.json({ ok: true, updatedCount: updated.length, updated, failed })
}
